CREATE TABLE IF NOT EXISTS evenement (
    id_event INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(180) NOT NULL,
    date_debut DATETIME NOT NULL,
    date_fin DATETIME NOT NULL,
    lieu VARCHAR(220) NOT NULL,
    capacite INT NOT NULL DEFAULT 1,
    type VARCHAR(80) NOT NULL DEFAULT 'General',
    statut VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    description TEXT,
    prix DECIMAL(10,2) NOT NULL DEFAULT 0,
    organizer_id INT DEFAULT 0,
    latitude DOUBLE DEFAULT 0,
    longitude DOUBLE DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS participation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    user_id INT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_participation_event_user (event_id, user_id)
);

ALTER TABLE evenement ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE evenement ADD COLUMN IF NOT EXISTS prix DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE evenement ADD COLUMN IF NOT EXISTS organizer_id INT DEFAULT 0;
ALTER TABLE evenement ADD COLUMN IF NOT EXISTS latitude DOUBLE DEFAULT 0;
ALTER TABLE evenement ADD COLUMN IF NOT EXISTS longitude DOUBLE DEFAULT 0;
ALTER TABLE participation ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED';
ALTER TABLE participation ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
